[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
oft = "35Nxm1pNWB1VfPtKYwU2YtMy17QD6m9DTHZwkQoSevr2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"
